platform :ios, '13.0' 
 
workspace 'App.xcworkspace' 
 
target 'App' do 
  project 'App.xcodeproj' 
  pod 'Capacitor', :path =
  pod 'CapacitorCordova', :path =
 
  target 'AppTests' do 
    inherit! :search_paths 
  end 
end 
